INSERT INTO users (first_name, last_name, email, avatar_image, cover_image, password, bio) VALUES 
('John', 'Smith', 'john@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/john_u8nwuz.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824072/covers/john_gdytav.jpg', '123', 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'), 
('Kenny', 'Yanb', 'kenny@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/kenny_b7jr4t.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824067/covers/kenny_kelqfp.jpg', '123', 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'), 
('Sara',  'Dar', 'sara@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/sara_plrv5c.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824069/covers/sara_ogz5ud.jpg', '123', 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'), 
('Tony', 'Jortons', 'tony@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/tony_c6vhxu.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824073/covers/tony_yerhcv.jpg', '123', 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'),
('Frankis', 'Potato', 'frankis@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/frankis_zpckhi.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824073/covers/frankis_sfgzsq.jpg', 123, 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'),
('Maria', 'Kane', 'maria@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/maria_rr19tp.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824073/covers/maria_xvqk0r.jpg', 123, 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'),
('Louella', 'Ingram', 'louella@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/louella_o5o9br.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824065/covers/louella_tapetr.jpg', 123, 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'),
('Myron', 'Short', 'myron@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/myron_wqztyv.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824073/covers/myron_bh37qq.jpg', 123, 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'),
('Polly', 'Griffith', 'polly@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/polly_cvxvbh.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824072/covers/polly_fc1dlt.jpg', 123, 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website'),
('Laura', 'Carpenter', 'laura@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/laura_gbmjca.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824070/covers/laura_mcfdoy.jpg', 123, 'Lorem Ipsum is the single greatest threat. We are not - we are not keeping up with other websites. Lorem Ipsum best not make any more threats to your website');