INSERT INTO users (first_name, last_name, email, avatar_image, cover_image, password, bio) VALUES 
('John', 'Smith', 'john@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/john_u8nwuz.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824072/covers/john_gdytav.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'I am a visual artist and a graphic designer who focuses on children''s illustrations, book covers, and fun graphics. I am available for book design, illustration, and other commissions. If you are interested in working with me, please send me a message!'), 
('Kenny', 'Yanb', 'kenny@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/kenny_b7jr4t.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824067/covers/kenny_kelqfp.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'By day I am a preschool teacher, but in my spare time I like to paint, do some photography, and make digital artwork. I love beaches, sunsets, and pina coladas. Not currently taking commissions.'), 
('Sara',  'Dar', 'sara@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/sara_plrv5c.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824069/covers/sara_ogz5ud.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'I am an artist and freelance graphic designer who specializes in unique portraiture. If you send me a message with a photograph of your friend/loved one and some information about them, I can create beautiful, unique, and specialized portraits. These make great gifts for birthdays, graduations, weddings, and so on. Hit that message button for more details.'), 
('Tony', 'Jortons', 'tony@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/tony_c6vhxu.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824073/covers/tony_yerhcv.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'Sup? My name is Tony and I mostly paint abstract stuff.'),
('Frankis', 'Potato', 'frankis@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/frankis_zpckhi.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824073/covers/frankis_sfgzsq.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'I specialize in pen and ink drawings and I have a pretty unique style. I don''t really take commissions and prefer to just do my own thing. You can check out my art in my gallery.'),
('Maria', 'Kane', 'maria@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/maria_rr19tp.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824073/covers/maria_xvqk0r.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'I am a psychoanalyst and a literature professor, but in my spare time I love to paint. These are some paintings I have made of people that I love. I do take commissions, but please remember that paintings like these take a lot of time, so if you are shopping for a special occasion or a project with a firm deadline, please let me know as far in advance as possible. Thanks!'),
('Louella', 'Ingram', 'louella@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/louella_o5o9br.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824065/covers/louella_tapetr.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'I am just a casual painter looking to make a few extra $$. Message me for commissions, or shop my page for more details.'),
('Myron', 'Short', 'myron@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/myron_wqztyv.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824073/covers/myron_bh37qq.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'Hi!! I specialize in commission paintings for marketing agencies looking for reasonably priced fine and custom art. I work on a by-commission basis, but I do have a few paintings in my gallery if you are interested in browsing.'),
('Polly', 'Griffith', 'polly@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/polly_cvxvbh.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824072/covers/polly_fc1dlt.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'I make digital art that tricks the eye. Message me for more details.'),
('Laura', 'Carpenter', 'laura@mail.com', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824256/avatars/laura_gbmjca.jpg', 'https://res.cloudinary.com/dckcnn64n/image/upload/v1664824070/covers/laura_mcfdoy.jpg', '$2b$10$.VIO0NQGR/scAtFFVtzHCuIC5Jx9k8c1Fp0pn9vIr8xjuR3oOn2TO', 'Hi there! My name is Laura and I am a freeland graphic designer and illustrator by trade. I have done work for a ton of major brands for marketing, packaging, and website design, but I also do a lot of work with design firms, book publishers, and merchandisers. I am available Monday through Friday from 9:00am to 4:00pm and do not answer emails on weekends. If you are interested in signing me on for a larger project, please send me an email using the message button. But, I do also have some images on my page for shopping or reference. Looking forward to working with you!');